### ISSUE TITLE
Joinmarket does not connect to bitcoind on Raspiblitz

### ISSUE THREAD

**Issue by gcomte** [openoms/bitcoin-tutorials#27]
**Raspiblitz 1.3
JoinMarket 0.6.1**

When I try to `python wallet-tool.py generate` the second time (following your description) I get the following error message:

```
Traceback (most recent call last):
  File "wallet-tool.py", line 10, in <module>
    load_program_config()
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/configure.py", line 478, in load_program_config
    global_singleton.config)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/configure.py", line 532, in get_blockchain_interface_instance
    bc_interface = BitcoinCoreInterface(rpc, network)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/blockchaininterface.py", line 166, in __init__
    blockchainInfo = self.jsonRpc.call("getblockchaininfo", [])
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/jsonrpc.py", line 148, in call
    response = self.queryHTTP(request)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/jsonrpc.py", line 106, in queryHTTP
    raise exc
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/jmclient/jsonrpc.py", line 94, in queryHTTP
    "authentication for JSON-RPC failed")
jmclient.jsonrpc.JsonRpcConnectionError: authentication for JSON-RPC failed
```

I have set `rpcuser = raspibolt` and the `rpcpassword` in `/home/admin/joinmarket-clientserver/scripts/joinmarket.cfg`.

Any ideas?

**Comment by openoms** [comment]
Are you following this guide: https://github.com/openoms/bitcoin-tutorials/blob/master/joinmarket/README.md?

It shows that is an authentication problem.
Double check the password in `joinmarket.cfg` against the `/mnt/hdd/bitcoin/bitcoin.conf` and that you are connecting to the localhost.

**Comment by gcomte** [comment]
Yes this guide.

Yes, the configs seem to be correct ..

`/mnt/hdd/bitcoin/bitcoin.conf`:
```rpcuser=raspibolt
rpcpassword=xxx
rpcport=8332
rpcallowip=127.0.0.1
rpcbind=127.0.0.1:8332
```

`/home/admin/joinmarket-clientserver/scripts/joinmarket.cfg`:
```blockchain_source = bitcoin-rpc
rpc_host = localhost
rpc_port = 8332
rpcuser = raspibolt
rpcpassword = xxx
```

**Comment by openoms** [comment]
If you updated to the latest Bitcoin Core 0.19.0.1 try modifying the bitcoin.conf to:
```
main.rpcport=8332
main.rpcbind=127.0.0.1:8332
main.bind=127.0.0.1
```
and retstart bitcoind:
`sudo systemctl restart bitcoind`
