### ISSUE TITLE
Is yield generator running? Can't detach from tmux

### ISSUE THREAD

**Issue by pretyflaco** [openoms/bitcoin-tutorials#29]
Running JM on raspiblitz v1.5rc1
Created JM wallet and deposited 0.01 on mixdepth 0 address which has >5 confirmations 

```
# To run a yield generator with tmux
$ tmux
# Output 
bash: startup.sh: No such file or directory
$ python yg-privacyenhanced.py wallet.jmdat
# Output 
File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/yieldgenerator.py", line 29, in __init__
    Maker.__init__(self, wallet_service)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/maker.py", line 32, in __init__
    self.sync_wait_loop.start(2.0)
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/maker.py", line 48, in try_to_create_my_orders
    sys.exit(EXIT_FAILURE)
builtins.SystemExit: 1

2020-04-11 21:38:33,953 [INFO]  starting yield generator
2020-04-11 21:38:34,146 [INFO]  Listening on port 27183
2020-04-11 21:38:34,147 [INFO]  Starting transaction monitor in walletservice
2020-04-11 21:38:40,150 [INFO]  joined: #joinmarket-pit tor.darkscience.net
2020-04-11 21:38:40,152 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2020-04-11 21:38:40,607 [INFO]  joined: #joinmarket-pit guybrush.hackint.org
2020-04-11 21:38:40,608 [INFO]  All IRC servers connected, starting execution.
```
Is yield generator running? 
Detaching from tmux with ctrl+b,d does not work for some reason. 
Closing terminal and resuming session in new terminal works with
`$ tmux a `

After some time:
```
#output
2020-04-11 21:48:38,614 [INFO]  Failed to start after 10 minutes, giving up.
2020-04-11 21:48:38,616 [INFO]  Lost IRC connection to: guybrush.hackint.org . Should reconnect automatically soon.
2020-04-11 21:48:38,618 [INFO]  Lost IRC connection to: tor.darkscience.net . Should reconnect automatically soon.
done
```

Checking addresses in wallet shows 0.01 hasn't moved, still sitting in mixdepth 0. 
Any idea what I'm missing?

Edit: Not sure, if this is the right place to ask this. If it's not, a hint in the right direction is appreciated :)

**Comment by openoms** [comment]
Use tmux after entering the joinmarket user.
`sudo su - joinamarket`

`tmux`

make sure the (jmvenv) virtual environment is active before running the joinmarket scripts.

The prompt looks like this when jmvenv is active:
`(jmvenv) joinmarket@raspberrypi:~/joinmarket-clientserver/scripts $`

This is  my output running the YG in tmux as described above:
```
bash: startup.sh: No such file or directory
(jmvenv) joinmarket@raspberrypi:~/joinmarket-clientserver/scripts $ python yield-generator-basic.py jm1.jmdat
User data location: /home/joinmarket/.joinmarket/
Enter wallet decryption passphrase: 
2020-04-11 22:40:32,330 [INFO]  offerlist=[{'oid': 0, 'ordertype': 'swreloffer', 'minsize': xxxxxx, 'maxsize': xxxxxx, 'txfee': xxx, 'cjfee': 'xxxxxx'}]  
2020-04-11 22:40:32,334 [INFO]  starting yield generator
2020-04-11 22:40:32,773 [WARNING]  Cannot listen on port 27183, trying next port
2020-04-11 22:40:32,776 [INFO]  Listening on port 27184
2020-04-11 22:40:32,778 [INFO]  Starting transaction monitor in walletservice
2020-04-11 22:40:38,981 [INFO]  joined: #joinmarket-pit tor.darkscience.net
2020-04-11 22:40:38,983 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2020-04-11 22:40:45,925 [INFO]  joined: #joinmarket-pit guybrush.hackint.org
2020-04-11 22:40:45,925 [INFO]  All IRC servers connected, starting execution.
2020-04-11 22:40:45,931 [INFO]  JM daemon setup complete
```



The IRC servers have failures form time to time. They will reconnect.

You should see your offer up at:
joinmarket.me/ob

**Comment by openoms** [comment]
CTRL + b, d works on my setup as normal.

**Comment by openoms** [comment]
It is good to raise these UX issues.
Made a few changes to help:
https://github.com/openoms/bitcoin-tutorials/commit/e0a24daac5b4f48dc20ef67fc4097552ad97c71a
https://github.com/rootzoll/raspiblitz/pull/1115

**Comment by pretyflaco** [comment]
Glad you find this helpful. 
Instead of the privacyenhanced, I tried the normal YG as described above, find output below after `tmux`:

```
bash: startup.sh: No such file or directory
(jmvenv) joinmarket@raspberrypi:~/joinmarket-clientserver/scripts $ python yield-generator-basic.py wallet.jmdat
User data location: /home/joinmarket/.joinmarket/
Enter wallet decryption passphrase:
2020-04-11 23:13:16,337 [INFO]  minsize (7499999) > maxsize (972700)
2020-04-11 23:13:16,340 [INFO]  Failed to create offers, giving up.
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/yieldgenerator.py", line 29, in __init__
    Maker.__init__(self, wallet_service)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/maker.py", line 32, in __init__
    self.sync_wait_loop.start(2.0)
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/maker.py", line 48, in try_to_create_my_orders
    sys.exit(EXIT_FAILURE)
builtins.SystemExit: 1

2020-04-11 23:13:16,367 [INFO]  starting yield generator
2020-04-11 23:13:16,698 [INFO]  Listening on port 27183
2020-04-11 23:13:16,700 [INFO]  Starting transaction monitor in walletservice
2020-04-11 23:13:22,068 [INFO]  joined: #joinmarket-pit tor.darkscience.net
2020-04-11 23:13:22,070 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2020-04-11 23:13:23,176 [INFO]  joined: #joinmarket-pit guybrush.hackint.org
2020-04-11 23:13:23,178 [INFO]  All IRC servers connected, starting execution.
2020-04-11 23:23:21,182 [INFO]  Failed to start after 10 minutes, giving up.
2020-04-11 23:23:21,186 [INFO]  Lost IRC connection to: guybrush.hackint.org . Should reconnect automatically soon.
2020-04-11 23:23:21,192 [INFO]  Lost IRC connection to: tor.darkscience.net . Should reconnect automatically soon.
done
```

**Comment by openoms** [comment]
Using the `yg-privacyenhanced.py` is preferred since it it randomizing the parameters within the set limits.

Read the output:
```
2020-04-11 23:13:16,337 [INFO]  minsize (7499999) > maxsize (972700)
2020-04-11 23:13:16,340 [INFO]  Failed to create offers, giving up.
```

Your minsize is higher than what is in the wallet. Edit it in the yield-genarerator/yg-privacyenhanced.py.

Have a look at the orderbook to have some idea about the viable offer amounts.

Also the funds will spread out between the mixdepths with time.

**Comment by pretyflaco** [comment]
I think this solved it.
Minsize was set to 1000000 (1million) by default in `yg-privacyenhanced.py`. 
Lowered to 100000 and I got the following output:

```
User data location: /home/joinmarket/.joinmarket/
Enter wallet decryption passphrase:
2020-04-12 01:09:49,404 [INFO]  offerlist=[{'oid': 0, 'ordertype': 'swabsoffer', 'minsize': 99431, 'maxsize': 879869, 'txfee': 73, 'cjfee': '530'}]
2020-04-12 01:09:49,407 [INFO]  starting yield generator
2020-04-12 01:09:49,643 [INFO]  Listening on port 27183
2020-04-12 01:09:49,646 [INFO]  Starting transaction monitor in walletservice
2020-04-12 01:09:54,307 [INFO]  joined: #joinmarket-pit tor.darkscience.net
2020-04-12 01:09:54,310 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2020-04-12 01:09:54,970 [INFO]  joined: #joinmarket-pit guybrush.hackint.org
2020-04-12 01:09:54,972 [INFO]  All IRC servers connected, starting execution.
2020-04-12 01:09:54,979 [INFO]  JM daemon setup complete
```

Found my offer on Orderbook.

**Comment by openoms** [comment]
Glad this is solved, closing now.

Good for further reading: https://github.com/JoinMarket-Org/joinmarket/wiki/Running-a-Yield-Generator
