### ISSUE TITLE
Wallet creation failing using JoininBox

### ISSUE THREAD

**Issue by CoderBoogs** [openoms/bitcoin-tutorials#31]
Trying to create a test wallet to experiemnt with joinmarket and when i create a wallet the following error comes up 

Running the command:Running the command:
 python wallet-tool.py    history

User data location: /home/joinmarket/.joinmarket/
Traceback (most recent call last):
  File "/home/joinmarket/joinmarket-clientserver/scripts/wallet-tool.py", line 6, in <module>
    jmprint(wallet_tool_main("wallets"), "success")
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/wallet_utils.py", line 1223, in wallet_tool_main
    wallet_password_stdin=options.wallet_password_stdin, gap_limit=options.gaplimit)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/wallet_utils.py", line 1114, in open_test_wallet_maybe
    return open_wallet(path, mixdepth=max_mixdepth, **kwargs)
  File "/home/joinmarket/joinmarket-clientserver/jmclient/jmclient/wallet_utils.py", line 1134, in open_wallet
    raise Exception("Failed to open wallet at '{}': not a file".format(path))
Exception: Failed to open wallet at '/home/joinmarket/.joinmarket/wallets/': not a file

how to fix?

**Comment by openoms** [comment]
Closing for inactivity.
Feel free to continue if running into problems.

**Comment by CoderBoogs** [comment]
fixed this issue as well. funded the wallet thanks @openoms
